# Generated by Django 5.0.12 on 2025-03-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0013_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='features',
            field=models.TextField(blank=True, help_text='Features for pricing separated by new line', null=True),
        ),
    ]
