name: 1 - Hello World Github actions

on:
  workflow_dispatch:
  push:
    branch:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello there
        run: echo "Hello World from Github Actions!"
