name: 1 - Hello World Github actions

on:
  workflow_dispatch:
  #schedule:
  #  - cron: '0 0 * * *' # Runs every day at midnight
  #push:
  #  branch:
  #    - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello there
        run: echo "Hello World from Github Actions!"
